### ISSUE TITLE
Is it possible to transfer the ownership to fluent-plugins-nursery?

### ISSUE THREAD

**Issue by daipom** [reevoo/fluent-plugin-systemd#104]
Hi @errm.
First, thanks for developing such a great plugin!

We are @fluent-plugins-nursery team who try to maintain Fluentd plugins and keep them updated.

It seems that the development of this plugin has been stagnating for a while.

Since this plugin is embedded in td-agent, we want to adopt this plugin.

So the question is: is it possible to transfer the ownership of this project to fluent-plugins-nursery?
If you can, we'd continue developing this work as part of our program to sustain the ecosystem.

For more information, please see here.

* https://github.com/fluent-plugins-nursery/contact#what-happens-if-i-transfer-my-plugin

We are looking forward to hearing back from you!

**Comment by daipom** [comment]
@errm Could you please see this?

**Comment by ksandrmatveyev** [comment]
@repeatedly @cosmo0920  Could you take a look as well?

**Comment by errm** [comment]
Hi sorry it took me a long time to see this!  Yes I am happy for other maintainers to join whenever!  Since I don't use this plugin myself anymore it would be good to keep it going!

**Comment by errm** [comment]
@daipom should I open an issue on https://github.com/fluent-plugins-nursery or will someone do that on your side?

**Comment by cosmo0920** [comment]
@errm We wrote the procedure of transferring onwership here: https://github.com/fluent-plugins-nursery/contact#how-to-transfer-your-plugin
Could you file an issue on https://github.com/fluent-plugins-nursery/contact/issues and proceed the described procedures?
Please keep us posted until the process is done.

**Comment by daipom** [comment]
@errm Thanks for your reply! 
Could you please open an issue by https://github.com/fluent-plugins-nursery/contact/issues/new?assignees=&labels=&projects=&template=transfer_request.md?

**Comment by daipom** [comment]
This is completed in https://github.com/fluent-plugins-nursery/contact/issues/32.
Thanks!
