### ISSUE TITLE
Add support for in_tail parser plugins (format_multiline)

### ISSUE THREAD

**Issue by mindw** [reevoo/fluent-plugin-systemd#11]
Merging mulltiline logs outside input plugins logs is very difficult see okkez/fluent-plugin-concat#8  for an explanation.

**Comment by errm** [comment]
I have no plans to add this functionality, as we do not allow for multiline logs in our(reevoo's) system.

I am happy to accept and review a PR if someone else wants to contribute it. I have had a look at the implementation in the in_tail plugin and it seems quite complex...

**Comment by errm** [comment]
I am closing this as given the direction the plugin has taken I don't even think I would accept code to do this so I don't want someone to work on this assuming that we would merge the code...
