### ISSUE TITLE
Port 'Continue Reading on Bad Messages' to 0.0.x branch

### ISSUE THREAD

**Issue by dannyk81** [reevoo/fluent-plugin-systemd#45]
Would be great if #41 could be ported to 0.0.x branch as we are hitting this with fluentd 0.12.x

Thanks!

**Comment by dannyk81** [comment]
@errm Sorry for nagging 😉 but any chance to see this back ported to 0.0.x soon? 🙏

**Comment by dannyk81** [comment]
Seems like https://github.com/reevoo/fluent-plugin-systemd/pull/49 should fix this, thanks @chancez

@errm can you take a look?

**Comment by errm** [comment]
Just released 0.0.9 to include the backport thanks to @chancez
