### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by errm** [reevoo/fluent-plugin-systemd#53]
This plugin has been used by an number of users e.g. https://github.com/fluent/fluentd-kubernetes-daemonset

It seems to be mostly stable so I am considering cutting a 1.0 branch and cleaning up a little of the backwards compatibility code e.g. https://github.com/reevoo/fluent-plugin-systemd/blob/master/lib/fluent/plugin/systemd/pos_writer.rb#L62

If there are any other issues/features that I need to look at before then please mention them now as I plan to favour stability over features once this goes 1.0

# TIMELINE:
- [x] Cut a 1.0.0 branch (March 2018)
- [x] Replace reevoocop with rubocop
- [x] Ensure tests are run against latest fluentd/systemd
- [x] Clean up deprecated config options and migration code (March - April 2018)
- [x] Do some pre-release versions (April - May 2018)
- [x] Improve Documentation
- [ ] Release 1.0.0 (by end of May 2018)

**Comment by emacski** [comment]
@errm,

I have noticed several instances where people are copying and pasting the example plugin configuration from the `README.md` as a starting point for configuration. I didn't really account for that when creating the somewhat arbitrary example `field_map`. I created the example to try and cover all the functionality of the mutator, but it's not very practical for real-world use. Do you think it's worth addressing that in the documentation before the 1.0 release?

Two possible solutions:
1. Try to construct a more practical example `field_map` that still illustrates all major functionality of the mutator
2. Remove the `field_map` entry config from the main config example and expand the documentation to cover the `field_map` further down the readme. I assume, but could be wrong, that the lowercasing and underscore stripping alone would be sufficient in the main example for the majority of "getting started" use cases.

**Comment by errm** [comment]
Good point @emacski, I will also work on improving the documentation pre 1.0.0
