### ISSUE TITLE
License change request (Apache License v2.0)

### ISSUE THREAD

**Issue by edsiper** [reevoo/fluent-plugin-systemd#60]
> answering @errm requirement

Fluentd organization and CNCF are happy to receive this plugin and hosted it under the official fluent/ organization. The only requirement is the license change to Apache License v2. If all authors agreed on that and the license is changed, we can start the transition.

**Comment by errm** [comment]
@cosmo0920 
@repeatedly 
@emacski 
@Jitsusama 
@mikekap
@neko-neko
@jescarri

You have all contributed code to this plugin could you please comment below indicating that you are happy for me to relicense your code as Apache License v2.

If you are unhappy for some reason please also comment so I can take action to replace your code...

**Comment by Jitsusama** [comment]
I personally use Apache 2 on all of my own projects. I prefer true freedom to chained freedom (yes, I’m speaking about you GPL!)

**Comment by errm** [comment]
Currently the plugin is MIT licensed... Mainly because this is fairly much the default choice in the Ruby world... AFAIKT it is much the same as Apache just without the Patent grant stuff... but clearly contributor consent is the key thing here before we change anything.

**Comment by repeatedly** [comment]
I'm ok for Apache 2 :)

**Comment by cosmo0920** [comment]
I'm also OK for Apache-2.0 license. :smile:

**Comment by mikekap** [comment]
I'm ok relicensing under the Apache 2.0 license.

**Comment by emacski** [comment]
I'm ok with Apache 2.0 license as well

**Comment by errm** [comment]
Also @richm are you OK with moving to Apache 2.0, sorry I missed you yesterday... I was tiered?

**Comment by neko-neko** [comment]
I'm ok for Apache2 license :)

**Comment by richm** [comment]
@errm yes, Apache 2.0 is fine

**Comment by errm** [comment]
Oops missed one more person ... ping @jtwile2 re this ... you didn't show up in the contributors thing in github... but I remember your PR :)

**Comment by errm** [comment]
@jtwile2 & @jescarri it would be great to hear if you are ok with us relicensing this plugin with the Apache 2.0 license so we can transfer it to the fluentd organisation...

If I don't hear within a week or so I will remove the code in question from the project ...

**Comment by errm** [comment]
Ok I said a week... but I went ahead and rewrote a few lines so we can push forward with this ... the 1.0.0 branch is now relicensed as Apache 2.0.

Thank you to everyone for coming forward quickly and making this so painless...
