### ISSUE TITLE
Corrupted pos file

### ISSUE THREAD

**Issue by serathius** [reevoo/fluent-plugin-systemd#68]
Forced termination caused corruption of pos file. Mutations to pos file could be done atomically to increase reliability.  

`fluent-plugin-systemd` version 1.0.1

From Logs
```
2018-07-05 07:02:41 +0000 [error]: [systemd.log] failed to read data from plugin storage file path="/var/log/systemd.log.pos" error_class=Yajl::ParseError error="lexical error: invalid char in json text.\n                                       s=97c17292555e41258bd6733e9836c\n                     (right here) ------^\n"
2018-07-05 07:02:41 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Unexpected error: failed to read data from plugin storage file: '/var/log/systemd.log.pos'"
```

**Comment by errm** [comment]
Humm... seems like an issue I agree

Right now we use fluentd's storage plugin system, so I don't think we have this level of control over how the file is written... but I will dig into it a little in the week and see if it is something that can be fixed upstream or if there is a way to configure the file storage to be atomic ...

If we did have atomic writes here though I suspect we would more often miss a cursor write in this case perhaps increasing the number of double reads ... but I do think that it is overall the best strategy if we can find a way...

As far as I can remember I think we try to ignore incorrect cursors and resume reading from the head or tail of the journal as a best effort, I guess we should also catch this sort of error (where it seems that the format of the storage file itself is corrupted rather than the cursor just being a nonsense value) and do the same.

**Comment by errm** [comment]
Assuming you are using the standard local storage plugin it does indeed seem to do atomic writes, the implementation here seems to be correct on first reading...

https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/storage_local.rb#L130-L132

@serathius Could you explain a bit more about the environment where you saw this (esp the configuration for the position storage) and if you were able to reproduce the error? or is it a one off?

**Comment by bobziuchkovski** [comment]
He might have switched his config from using the older `pos_file` param to the newer `<storage>` block and pointed at the same position file.  I ran into the exact same error message when I tested that transition myself.  Or he might be encountering something else...

**Comment by errm** [comment]
Thanks for the info @bobziuchkovski ... we should add this to https://github.com/reevoo/fluent-plugin-systemd#common-issues

**Comment by nulltrope** [comment]
Hi I am seeing a similar error reading the pos file
```
2018-10-18 20:38:01 +0000 [error]: failed to read data from plugin storage file path="/fluentd/pos/fluentd-journald.pos/worker0/storage.json" error_class=Fluent::ConfigError error="Invalid contents (not object) in plugin storage file: '/fluentd/pos/fluentd-journald.pos/worker0/storage.json'"
2018-10-18 20:38:01 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unexpected error: failed to read data from plugin storage file: '/fluentd/pos/fluentd-journald.pos/worker0/storage.json'"
``` 
however in this case, the file itself exists on the host but it is empty. This is resulting in my fluentd containers crashlooping. Removing the storage.json and restarting seems to fix, will see if this issue crops up again.

**Comment by errm** [comment]
Thanks @jekohk ... I will take a look at this again and see if there is something we can do here to fix this ...

**Comment by Tim017** [comment]
we met the same issue here - 'fluentd container crashlooping', any update or clue to fix it?

**Comment by Michake** [comment]
I met the same issue when 'fluentd container crashlooping', any update?

**Comment by vladimir-kozyrev** [comment]
Same issue here.
We've got the file in place but it is empty. fluentd is crashing because of this.
```
2018-12-06 10:48:34 +0000 [error]: [in_systemd_kubelet] failed to read data from plugin storage file path="/var/log/fluentd-journald-kubelet-cursor.json" error_class=Fluent::ConfigError error="Invalid contents (not object) in plugin storage file: '/var/log/fluentd-journald-kubelet-cursor.json'"
2018-12-06 10:48:34 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unexpected error: failed to read data from plugin storage file: '/var/log/fluentd-journald-kubelet-cursor.json'"
```

**Comment by nulltrope** [comment]
Hi any updates on this? 
Still causing issues for us, empty cursor file prevents the fluentd from restarting

**Comment by arslanbekov** [comment]
Hi any updates on this?

**Comment by mojotx** [comment]
Following. We've seen this as well.

**Comment by yuripastushenko** [comment]
We also have the same problem.
Once in 2-3 weeks, we are forced to delete the corrupted file for problem fixing.
Any updates?

**Comment by grjones** [comment]
This is also happening for me fairly often, probably every couple of weeks.  For me, I'm running fluentd on a VM, so the VM stopping or pausing is frequent which may be a contributing factor.

**Comment by errm** [comment]
@jekohk @Arslanbekov @mojoTX @yuripastushenko @grjones Could you share the storage config you are using... As I mentioned before if you are using the standard local storage plugin writes should be atomic...

**Comment by schmidtjohannes** [comment]
We are facing the same issue on centos 7 with k8s 1.12 using daemonset with fluent/fluentd-kubernetes-daemonset:v1.3.2-debian-elasticsearch: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/245.

**Comment by errm** [comment]
Seems this was an issue with fluentd that was patched upstream, updating to the latest fluentd should fix!

**Comment by zhasik911** [comment]
Hi, everyone!!! We have the problem. Fluent display message 
```
#0 [in_systemd_kubelet] failed to save data for plugin storage to file path="/var/log/fluentd-journald-kubelet-cursor.json" tmp="/var/log/fluentd-journald-kubelet-cursor.json.tmp" error_class=Errno::ENOENT error="No such file or directory @ rb_file_s_rename - (/var/log/fluentd-journald-kubelet-cursor.json.tmp, /var/log/fluentd-journald-kubelet-cursor.json)"
```
 fluent version is fluent/fluentd-kubernetes-daemonset:v1.7-debian-elasticsearch6-1. Have you any idea??

**Comment by kumarganesh2814** [comment]
`2019-10-26 18:45:41 +0000 [error]: #0 failed to save data for plugin storage to file path="/var/log/fluentd-systemdlog.pos/worker0/storage.json" tmp="/var/log/fluentd-systemdlog.pos/worker0/storage.json.tmp" error_class=Errno::ENOENT error="No such file or directory @ rb_file_s_rename - (/var/log/fluentd-systemdlog.pos/worker0/storage.json.tmp, /var/log/fluentd-systemdlog.pos/worker0/storage.json)"`

Getting same Error 

Using below:
        fluent-plugin-kubernetes_metadata_filter:2.3.0 \
        fluent-plugin-rewrite-tag-filter:2.2.0 \
        fluent-plugin-systemd:1.0.2 \
        fluent-plugin-vmware-loginsight:0.1.6
