### ISSUE TITLE
Duplicate entries from journald in 0.0.11

### ISSUE THREAD

**Issue by loburm** [reevoo/fluent-plugin-systemd#72]
Our team have found the issue in one of our fluentd images. Steps to reproduce:
1. Create file /etc/fluent/fluent.conf with content
```
<source>
    type systemd
    filters [{ "_SYSTEMD_UNIT": "docker.service" }]
    pos_file /var/log/gcp-journald-docker.pos
    read_from_head true
    tag docker
</source>

<match docker>
    @type stdout
</match>
```

2. Run command: docker run -ti --rm -v /etc/fluent/fluent.conf:/etc/fluent/fluent.conf -v /usr/lib64:/host/lib -v /var/log:/var/log --network=host gcr.io/google-containers/fluentd-gcp:2.0.18

It's going to print latest message from docker every second.

If use version 2.0.17 instead we don't see the same problem. Biggest difference between those two images is systemd gem (0.0.11 vs 0.0.9)

**Comment by errm** [comment]
Do you have some sample of the fluentd logs you could share ... it sounds perhaps like something is crashing/erring and its just retried every second ...
