### ISSUE TITLE
Support customizing `pos_file` path

### ISSUE THREAD

**Issue by qingling128** [reevoo/fluent-plugin-systemd#78]
[Problem]
When specifying a customized `pos_file` for in_systemd plugin, the value gets ignored.

[Version]
gem 'fluent-plugin-systemd' version '1.0.2'

[Config]
```
  <source>
    @type systemd
    filters [{"_SYSTEMD_UNIT":"docker.service"}]
    pos_file /var/log/k8s-gcp-journald-docker.pos
    read_from_head true
    tag "docker"
  </source>
```

[Warnings in the log]
```
2019-07-25 16:22:39 +0000 [warn]: parameter 'pos_file' in <source>
  @type systemd
  filters [{"_SYSTEMD_UNIT":"docker.service"}]
  pos_file /var/log/k8s-gcp-journald-docker.pos
  read_from_head true
  tag "docker"
</source> is not used.
```

**Comment by qingling128** [comment]
Ah, in fact this is out-of-date. I think I just need to use https://docs.fluentd.org/storage.

**Comment by errm** [comment]
Yes with the current version of the plugin you can just use any storage plugin
