### ISSUE TITLE
Not able to ship logs even after adding td-agent user to systemd-journal group

### ISSUE THREAD

**Issue by somasusr** [reevoo/fluent-plugin-systemd#86]
Hi @errm we are facing issue in shipping logs from systemd. We have followed all the instructions and added "td-agent" user to "systemd-journal" group. Ours is Centos box and we have installed td-agent version 3 (td-agent.x86_64 3.8.0-0.el7). Looks like permission issue and when we add "td-agent" user to "root" group it works. Do we really need to provide root access to td-agent service for this plugin to work? Can you please help us in this?

Regards,
Sri Ramanathan

**Comment by errm** [comment]
What do the permissions on the files in `/var/log/journal` look like?

**Comment by somasusr** [comment]
@errm We figured this and it worked after we set permission to "td-agent" user for "/var/log/journal". Thank you for your response.
